version: 2

sources:
  - name: ghcnm
    database: dbtlabsprojects
    schema: "10_25"
    tables:
      - name: ghcnm_tavg
      - name: ghcnm_tavg_stations
      - name: ghcnm_tmax
      - name: ghcnm_tmax_stations
      - name: ghcnm_tmin
      - name: ghcnm_tmin_stations
